/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * zod-openapi-play
 * OpenAPI spec version: 1.0.0
 */

export interface CreateUser {
  email: string;
  /** @minLength 1 */
  name: string;
}
